<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>中国象棋--<?php echo $name."房间";?></title>
    <link rel="stylesheet" href="./css/room.css">
    <script src="./jquery/jquery-3.3.1.js"></script>
    <script src="./js/chessrules.js"></script>
    <script>
        var allow_load = <?php
            if(($username == $guest && $flag == "guest") || ($username == $host && $flag == "host"))
                echo 0;
            else
                echo 1;
            ?>;
        var site = "<?php echo $username != $host?'guest':'host';?>";
        var site_num = "<?php echo $username == $guest?'0':'1';?>";
        //房主：红棋（1），客人：黑棋（0）
        var flag = "<?php echo $flag;?>";//初始化标记变量
        var guest = "<?php echo $guest;?>";//获取黑棋玩家名称
        var host = "<?php echo $host;?>";//获取红棋玩家名称
        var now_chess = "";//初始化当前棋子的变量为空
        var moved = "";//初始化移动棋子的变量为空
        var eated = "";//初始化吃棋的变量
        var pause_time = 0;//初始化发布信息的时间
        var prompt_pause_time = 0;//初始化提示信息的时间
        var guest_win = <?php echo $guest_win;?>;//黑棋方的赢局次数
        var host_win = <?php echo $host_win;?>;//红棋方的赢局次数
        var game_ended = 0;//初始化游戏结束标记
        var t3 = "";
        function form_chess(chess){       			//自定义函数
            now_chess = chess;						//对当前棋子的变量重新赋值
            var chess_split = chess.split(",");		//分割棋子字符串为数组
            var pla = "<table width=556 height=601 border=0 cellpadding=0 cellspacing=0 bordercolor=#000000 background=images/bg.png><tr><td><table align=center border=0 cellpadding=0 cellspacing=0 width=540 height=601>";
            if(site == "host")
                for(var i = 0;i < 10;i ++){       //设置棋盘中主机的棋子10行9列，并布置主机棋子位置
                    pla += "<tr>";
                    for(j = 0;j < 9;j ++){
                        pla += "<td><div id=chess_"+(i * 9 + j + 1)+"><input type=hidden name=chess_value_"+(i * 9 + j + 1)+" id=chess_value_"+(i * 9 + j + 1)+" value="+chess_split[i * 9 + j]+"><a href=javascript:click_chess("+(i * 9 + j + 1)+")><img alt="+chess_split[i * 9 + j]+","+(i * 9 + j + 1)+" src=images/"+chess_split[i * 9 + j]+".png border=0 width=58px height=58px></a></div></td>";
                    }
                    pla += "</tr>";
                }
            else
                for(var i = 9;i >= 0;i --){        //设置棋盘中客机的棋子10行9列，并布置客机棋子位置
                    pla += "<tr>";
                    for(j = 8;j >= 0;j --){
                        pla += "<td><div id=chess_"+(i * 9 + j + 1)+"><input type=hidden name=chess_value_"+(i * 9 + j + 1)+" id=chess_value_"+(i * 9 + j + 1)+" value="+chess_split[i * 9 + j]+"><a href=javascript:click_chess("+(i * 9 + j + 1)+")><img alt="+chess_split[i * 9 + j]+","+(i * 9 + j + 1)+" src=images/"+chess_split[i * 9 + j]+".png  border=0 width=58px height=58px></a></div></td>";
                    }
                    pla += "</tr>";
                }
            pla += "</table></td></tr></table>";
            return pla;
        }
        //初始化上一个单机棋子的变量
        var prev_click ="";
        //初始化闪烁棋子的变量
        var chess_flash="";
        //初始化闪烁状态的变量
        var flash_status = 0;
        //初始化黑方玩家聊天信息的变量
        var message_guest = "";
        //初始化红方玩家聊天信息的变量
        var message_host = "";
        // 初始化黑方玩家上一条聊天信息
        var prev_message_guest = "";
        // 初始化红方玩家上一条聊天信息
        var prev_message_host = "";
        //创建单击棋子操作
        function click_chess(num) {
            if (site != flag){
                //如果当前的site值不等于棋子的走棋标记，弹出提示框信息提示
                open_prompt("对方走棋",'40%','2%');
                //    否则执行走棋操作
            } else {
                //关闭提示框
                close_prompt();
                //将棋子定义为可见
                for (var i= 1;i<91;i++)
                    document.getElementById("chess_"+i).style.visibility = "visible";
                //将闪烁棋子的变量定义为空
                chess_flash = "";
                if (document.getElementById("chess_value_"+num).value.substr(0,1) == site_num){
                    //将当前棋子定义为闪烁棋子
                    chess_flash = num;
                    //记录棋子当前位置
                    prev_click  = num;
                }else{
                    if (prev_click !=""){
                        //如果棋子走法不对则弹出提示框
                        if(!check(document.getElementById('chess_value_'+prev_click).value,prev_click,num)){
                            open_prompt("您的操作有误..........",'40%','2%');
                        }else{
                            //执行吃棋子操作，将房间号棋子原始坐标目的坐标传递到submit.php文件当中
                            send_request("submit.php?roomid=<?php echo $_GET['id'];?>&from="+prev_click+"&to="+num+"&site="+site+"&time="+Math.random());
                            //为变量赋值
                            allow_load = 1;
                            //将上一点击其次设置为空
                            prev_click ="";
                        }
                    }else {
                        //打开提示框
                        open_prompt("这不是您的棋子。",'40%','2%')
                    }
                }

            }
        }

        //初始化变量
        var prompt_count=0;
        //输出提示框所在位置
        function open_prompt(message,top,left) {
            //标量赋值为1
            prompt_count = 1;
            //计时器按1+秒计算
            prompt_pause_time ++;
            //如果聊天记录不为空
            if (message){
                //设置元素的可见
                document.getElementById('item').style.visibility = "visible";
                //设置元素的居中显示
                document.getElementById('item').style.align ="center";
                //设置元素的顶部距离
                document.getElementById('item').style.top = top;
                //设置元素的左侧距离
                document.getElementById('item').style.left = left;
                //设置元素中显示的内容
                document.getElementById('item').innerHTML = '<table class="message_box"><tr><td valign=middle>系统提示：<br><br>&nbsp;&nbsp;'+message+'</td></tr></table>';
            }
        }
        function close_prompt(){         //关闭提示信息，设置为隐藏
            document.getElementById("item").style.visibility = "hidden";//设置元素为隐藏
            document.getElementById("item").innerHTML =  '';//设置元素中的内容为空
            prompt_pause_time = 0;          //计时功能初始化为0
        }
        var http_request = false;
        function send_request(url) {
            open_prompt((prompt_pause_time > 0?'等待对方响应'+prompt_pause_time+'秒':''), '40%', '2%');
            //创建XMLHTTPRequest对象
            if (window.XMLHttpRequest){
                http_request = new XMLHttpRequest();
                if(http_request.overrideMimeType){
                    http_request.overrideMimeType('text/xml');
                }
                //    创建XMLHTTP对象
            }else if (window.ActiveXObject){
                try{
                    http_request =new ActiveXObject("Msxml2.XMLHTTP");
                }catch (e) {
                    try{
                        http_request = new ActiveXObject("Microsoft.XMLHTTP");
                    }catch (e) {}
                }
            }
            //如果http_request的值为假,则不能创建对象
            if (!http_request){
                alert ('不能创建XMLHttpRequest对象');
                return false;
            }
            //制定回调方法
            http_request.onreadystatechange = processRequest;
            //用GET方法提交数据
            http_request.open('GET',url,true);
            //发送信息为空
            http_request.send(null);
        }
        //定义创建一个DIV的变量
        var resultDiv;
        //定义一个空数组
        var text = new Array();
        //设置棋盘中的信息提示框
        function processRequest() {
            //若请求已经完成,若请求已经发送成功
            if (http_request.readyState == 4 && http_request.status == 200) {

                //如果返回的值为end
                if (http_request.responseText == "ended")
                //页面跳回到首页
                    document.location.href = "index.php";
                //将返回的值以|符号分开
                text = http_request.responseText.split("|");
                //如果返回的值为真
                if (http_request.responseText) {
                    //获取被吃了的棋子信息
                    t3 = text[3];
                    //获取黑方的聊天信息
                    message_guest = decodeURI(text[8]);
                    //获取红方的聊天信息
                    message_host = decodeURI(text[9]);
                    //获取黑方赢了的次数
                    guest_win = text[6];
                    //获取红方赢了的次数
                    host_win = text[7];
                    if (text[4] != guest) {
                        //若黑方玩家名称为空
                        if (text[4] == "") {
                            //发出提示框
                            open_prompt(guest + "退出房间！", "40%", "2%");
                            //将黑方玩家定义为空
                            guest = "";
                            //重置玩家时间
                            prompt_pause_time = 0;
                            //为变量赋值
                            allow_load = 0;
                        } else {
                            //发出提示框
                            open_prompt(text[4] + "进入房间", "40%", "2%");
                            //重新定义黑方玩家
                            guest = text[4];
                            //重新定义走棋标志
                            flag = text[1];
                            //为棋盘重新布局
                            document.getElementById("pla").innerHTML = form_chess(text[0]);
                        }
                    }
                    //若红方玩家名称有变化
                    if (text[5] != host) {
                        //若红方玩家名称为空
                        if (text[5] == "") {
                            //打开提示框
                            open_prompt(host + "对方退出房间，你已成为房主", "40%", "2%");
                            //将红方玩家定义为空
                            host = "";
                            //重置定义时间
                            prompt_pause_time = 0;
                            //给变量赋值
                            allow_load = 0;
                            //若当前操作玩家为黑方
                            if (site == 'guest') {
                                //过一秒重新加入游戏
                                setTimeout("location.href = 'join.php?roomid=<?php echo $_GET['id'];?>'", 1000);
                            }
                        }
                    }
                }
                if (now_chess != text[0] && text[0]) {
                    //    对棋子重新布局
                    document.getElementById("pla").innerHTML = form_chess(text[0]);
                    //    重新定义当前走棋标志
                    flag = text[1];
                    //重新定义当前移动棋子
                    moved = text[2];
                    //如果当前操作时要走棋的玩家
                    if (site == flag) {
                        //为变量赋值
                        allow_load = 0;
                    }
                    //当黑方将棋被吃时
                    if (text[3] == "000" && site == "guest") {
                        //创建div元素
                        resultDiv = document.createElement("div");
                        //为Div设置class属性
                        resultDiv.className = "imgDiv";
                        //    为div设置图片
                        resultDiv.innerHTML = "<img src='./images/failure.png' width='100%' height='100%'>";
                        //    向body中添加div元素
                        document.body.appendChild(resultDiv);
                        //    过三秒后移除div元素
                        setTimeout("document.body.removeChild(resultDiv)", 3000);
                        //    将被吃的棋子赋值变量给eated
                        eated = text[3];
                        //将游戏结束的变量定义为1
                        game_ended = 1;
                        //    为变量赋值
                        allow_load = 1;
                        //    将提示框中的时间定义为0
                        prompt_pause_time = 0;
                    } else if (text[3] == "100" && site == "host") {
                        //创建div元素
                        resultDiv = document.createElement("div");
                        //为Div设置class属性
                        resultDiv.className = "imgDiv";
                        //    为div设置图片
                        resultDiv.innerHTML = "<img src='./images/failure.png' width='100%' height='100%'>";
                        //    向body中添加div元素
                        document.body.appendChild(resultDiv);
                        //    过三秒后移除div元素
                        setTimeout("document.body.removeChild(resultDiv)", 3000);
                        //    将被吃的棋子赋值变量给eated
                        eated = text[3];
                        //将游戏结束的变量定义为1
                        game_ended = 1;
                        //    将提示框中的时间定义为0
                        prompt_pause_time = 0;
                    } else if (text[3] == "000" && site == "host") {
                        //创建div元素
                        resultDiv = document.createElement("div");
                        //为Div设置class属性
                        resultDiv.className = "imgDiv";
                        //    为div设置图片
                        resultDiv.innerHTML = "<img src='./images/success.png' width='100%' height='100%'>";
                        //    向body中添加div元素
                        document.body.appendChild(resultDiv);
                        //    过三秒后移除div元素
                        setTimeout("document.body.removeChild(resultDiv)", 3000);
                        //    将被吃的棋子赋值变量给eated
                        eated = text[3];
                        //将游戏结束的变量定义为1
                        game_ended = 1;
                        //    将提示框中的时间定义为0
                        prompt_pause_time = 0;
                    } else if (text[3] == "100" && site == "guest") {
                        //创建div元素
                        resultDiv = document.createElement("div");
                        //为Div设置class属性
                        resultDiv.className = "imgDiv";
                        //    为div设置图片
                        resultDiv.innerHTML = "<img src='./images/success.png' width='100%' height='100%'>";
                        //    向body中添加div元素
                        document.body.appendChild(resultDiv);
                        //    过三秒后移除div元素
                        setTimeout("document.body.removeChild(resultDiv)", 3000);
                        //    将被吃的棋子赋值变量给eated
                        eated = text[3];
                        //将游戏结束的变量定义为1
                        game_ended = 1;
                        //    将提示框中的时间定义为0
                        prompt_pause_time = 0;
                        //    如果有新的棋子被吃
                    } else if (text[3] && eated != text[3] && text[3] != 'blank') {
                        //将被吃的棋子赋值给变量eated
                        eated = text[3];
                    }
                }
            }
        }
        function send_message(){             //定义发送聊天信息的函数
            var message = document.getElementById('message').value;//获取玩家聊天信息
            if(message != ''){             //如果聊天信息不为空
                var message = encodeURI(encodeURI(message));//对聊天信息进行编码
                send_request('send_message.php?roomid=<?php echo $_GET['id'];?>&message='+message+'&site='+site+'&random='+Math.random());//将聊天信息存储在数据表中
                document.getElementById('message').value = '';                   //消息框清空
                open_prompt('消息发送成功！', '40%', '2%');                     //弹出消息框
            }
        }
    </script>
    <script src="./js/room.js" type="application/javascript"></script>
</head>
<body>
<table align="center" style="padding-top:5%;">
    <tr>
        <td width="210" rowspan="3" valign="top">
            <table width="191" height="100%" border="0" cellpadding="0" cellspacing="0">
                <tr valign="top">
                    <script>document.write("<td height=240 valign='bottom' nowrap background='images/"+(site=='host'?'left1':'left2')+".png'>")</script>
                    <table width="191" height="60" border="0">
                        <tr>
                            <th width="40" height="30" align="right" valign="middle"><div id="top_box_flag" width="100%"></div></th>
                            <th width="130" height="30" align="left" valign="middle"><div id="top_box" width="100%"></div></th>
                            <th width="22" height="30" align="left" valign="middle"></th>
                        </tr>
                        <tr>
                            <td height="30" align="left" valign="middle"></td>
                            <td height="30" align="left" valign="top"><div id="top_box_tongji" width="100%"></div></td>
                            <td height="30" align="left" valign="middle"></td>
                        </tr>
                    </table>
                    </td>
                </tr>
                <tr>
                    <td width="191" height="126" align="center">
                        <a href="javascript:copy_url()"><img src="images/left3.png" style="margin-top:6px;"></a>
                        <script>document.write("<a href=exit.php?roomid=<?php echo $_GET['id'];?>&site="+site+"><img src='images/btn_exit.png' width=90 height=39 style='margin-top:8px;'></a>");</script>
                        <script>if(site == "host") document.write("<a href=end.php?roomid=<?php echo $_GET['id'];?>><img src='images/btn_end.png' width=90 height=39 border=0></a>");</script><br>
                    </td>
                </tr>
                <tr valign="bottom">
                    <script>document.write("<td height=240 valign='bottom' nowrap background='images/"+(site=='host'?'left2':'left1')+".png'>")</script>
                    <table width="191" height="60" border="0">
                        <tr><th width="40" height="30" align="right"><div id=bottom_box_flag width=100%></div></th>
                            <th width="130" align="left"><div id=bottom_box width=100%></div></th>
                            <th width="22" align="left"></th>
                        </tr>
                        <tr><td height="30" align="left"></td>
                            <td height="30" align="left" valign="top"><div id=bottom_box_tongji width=100%></div></td>
                            <td height="30" align="left"></td>
                        </tr>
                    </table>
                    </td>
                </tr>
            </table>
        </td>
        <td width="3" rowspan="3" >
            <div id="pla"></div>
        </td>
        <td width="240" align="right" valign=top>
            <table style="position:relative;">
                <tr>
                    <td><img src="images/sign.png" width="220" height="63"></td>
                </tr>
                <tr>
                    <td><img src="images/roomcode.png" width="220" height="70"><div class="roomcode"><?php echo $name;?></div></td>
                </tr>
                <tr>
                    <td width="220" height="260"><div id="item" style="position:absolute; left:0px; top:0px; z-index:1; visibility: hidden;"></div></td>
                </tr>
                <tr>
                    <td width="220" height="201" valign=bottom>
                        <table class="message" cellspacing="0" cellpadding="0">
                            <tr align="left">
                                <td height="45" colspan="3" scope="col" valign=middle>&nbsp;</td>
                            </tr>
                            <tr>
                                <td width="15"></td>
                                <td><div id="message_pla" class="message_chat"></div></td>
                                <td width="15"></td>
                            </tr>
                            <tr>
                                <td height="45" colspan="3" valign="middle" class="message_td">
                                    <input type="text" id="message" name="message" size="18" onBlur="this.focus();" onKeyPress="if(event.keyCode==13) {document.getElementById('button').click();}" />
                                    <input name="button" id="button" type="button" class="message_btn" onClick="send_message()" value="发送" />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<script>
    //    每次显示五条信息
    var message_sum = 5 ;
    //定义空的数组
    var message_arr = new Array();
    //输出聊天信息
    function show_message(message) {
        // alert(message);
        var div = document.getElementById("message_pla");
        //如果聊天记录少于5条
        if (message_arr.length< message_sum){
            // 添加信息元素
            div.innerHTML += message;
            //输出全部信息
            message_arr[message_arr.length] = message;
            //滚动条始总保持在底部
            div.scrollTop = div.scrollHeight;
        } else {
            //利用for循环获取数组0~4的下标
            for (var i = 1; i<message_sum; i ++){
                message_arr[i - 1] = message_arr[i];
            }
            //将聊天记录储存在数组中，存取5条信息
            message_arr[message_sum - 1] = message;
            //将聊天记录设置为空
            div.innerHTML = "";
            //利用for循环输出数组中后五条信息
            for (var i = 1; i<message_sum; i ++){
                div.innerHTML += message_arr[i];
            }
            //将滚条始终在最底下
            div.scrollTop = div.scrollHeight;
        }
    }
    function get_info() {               //定义get_info()函数
        if(guest && message_guest && prev_message_guest != message_guest){  //如果黑棋玩家聊天信息有变化
            show_message(guest + ":" + message_guest+"<br />");//输出黑棋玩家聊天信息
            // alert(show_message(guest + ":" + message_guest+"<br />"));
            prev_message_guest = message_guest;//将当前聊天信息定义为上一条聊天信息
        }
        if(host && message_host && prev_message_host != message_host){ //如果红棋玩家聊天信息有变化
            show_message(host + ":" + message_host+"<br />");//输出红棋玩家聊天信息
            prev_message_host = message_host;//将当前聊天信息定义为上一条聊天信息
        }
        if (site == "guest") {                //如果执行当前操作的是黑棋玩家
            document.getElementById('top_box').innerHTML = "<font class='style4'>" + host + "</font>";//定义指定元素中的内容
            document.getElementById('bottom_box').innerHTML = guest;//定义指定元素中的内容
            document.getElementById('top_box_tongji').innerHTML = "<font class='style4'>获胜：" + host_win + " 局</font>";//定义指定元素中的内容
            document.getElementById('bottom_box_tongji').innerHTML = "获胜：" + guest_win + " 局";//定义指定元素中的内容
            if (flag == "guest") {             //如果当前要走棋的是黑棋玩家
                //黑棋玩家输出走棋图标
                document.getElementById('bottom_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                document.getElementById('top_box_flag').innerHTML = "";//将元素中的内容定义为空
            }
            else {
                //红棋玩家输出走棋图标
                document.getElementById('top_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                document.getElementById('bottom_box_flag').innerHTML = "";//将元素中的内容定义为空
            }
        } else if (site == "host") {               //如果执行当前操作的是红棋玩家
            document.getElementById('bottom_box').innerHTML = "<font class='style4'>" + host + "</font>";//定义指定元素中的内容
            document.getElementById('top_box').innerHTML = guest;//定义指定元素中的内容
            document.getElementById('bottom_box_tongji').innerHTML = "<font class='style4'>获胜：" + host_win + " 局</font>";//定义指定元素中的内容
            document.getElementById('top_box_tongji').innerHTML = "获胜：" + guest_win + " 局";//定义指定元素中的内容
            if (flag == "host") {              //如果当前要走棋的是红棋玩家
                //红棋玩家输出走棋图标
                document.getElementById('bottom_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                document.getElementById('top_box_flag').innerHTML = "";//将元素中的内容定义为空
            }
            else {
                //黑棋玩家输出走棋图标
                document.getElementById('top_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                document.getElementById('bottom_box_flag').innerHTML = "";//将元素中的内容定义为空
            }
        }
        if(chess_flash != ""){//如果闪烁棋子变量的值不为空
            if(flash_status == 0){//如果闪烁状态变量值为0
                document.getElementById("chess_"+chess_flash).style.visibility = "hidden";//将该棋子设置为隐藏
                flash_status = 1;//将闪烁状态变量值定义为1
            }else{
                document.getElementById("chess_"+chess_flash).style.visibility = "visible";//将该棋子设置为可见
                flash_status = 0;//将闪烁状态变量值定义为0
            }
        }
        if(moved){    //如果有棋子移动
            var moved_split = moved.split(",");//将moved值以逗号为分割符分割为数组
            document.getElementById("chess_"+moved_split[0]).className = "moved";  //为数组中第一个元素值添加样式
            document.getElementById("chess_"+moved_split[1]).className = "moved";  //为数组中第二个元素值添加样式
        }
        if(allow_load == 1){
            pause_time = 0;             //初始化变量
            send_request('get_info.php?roomid=<?php echo $_GET['id'];?>&site='+site+'&random='+Math.random());//获取棋盘信息
            //移除棋子的超链接开始标记<a>
            document.getElementById("pla").innerHTML = document.getElementById("pla").innerHTML.replace(/<a(.*?)>/ig, "");
            //移除棋子的超链接结束标记</a>
            document.getElementById("pla").innerHTML = document.getElementById("pla").innerHTML.replace(/<\/a>/ig, "");
        }
        if(pause_time == 3 || host == "" || guest == ""){
            pause_time = 0;//为变量赋值
            send_request('get_info.php?roomid=<?php echo $_GET['id'];?>&site='+site+'&random='+Math.random());       //获取棋盘信息
        }
        pause_time ++;          //计时器自加1操作
        if(prompt_count > 0){//如果变量值大于0
            if(prompt_count == 3){//如果变量值等于3
                prompt_count = 0;//将变量值重新定义为0
                close_prompt();//关闭提示框
            }else
                prompt_count ++;//将变量值执行加1操作
        }
        if(game_ended == 1)//如果游戏结束变量值为1
            game_ended ++;//将变量执行加1操作
        else if(game_ended == 2){//如果游戏结束变量值为2
            if(site == "host"){//如果执行当前操作的是红棋玩家
                if(t3 == "100")//如果红棋“帅”被吃
                    guest_win ++;        //黑棋方赢一场次，在数据表中加1
                else
                    host_win ++;         //红棋方赢一场次，在数据表中加1
                send_request("restart.php?roomid=<?php echo $_GET['id'];?>&guest_win="+guest_win+"&host_win="+host_win+'&random='+Math.random());     //记录当前棋盘胜负，重新开局
                game_ended = 0;//将游戏结束变量值定义为0
            }
        }
    }
    //为象棋 进行初始布局
    send_request('get_info.php?roomid=<?php echo $_GET['id'];?>&site='+site+'&random='+Math.random());
    get_info();
    //每隔1秒执行一次
    setInterval("get_info()",1000);
</script>
</body>
</html>