<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>中国象棋--<?php echo $name."房间";?></title>
    <link rel="stylesheet" href="./css/room.css">
    <script src="./jquery/jquery-3.3.1.js"></script>
    <script>
        var allow_load = <?php
            if(($username == $guest && $flag == "guest") || ($username == $host && $flag == "host"))
                echo 0;
            else
                echo 1;
            ?>;
        var site = "<?php echo $username != $host?'guest':'host';?>";
        var site_num = "<?php echo $username == $guest?'0':'1';?>";
        //房主：红棋（1），客人：黑棋（0）
        var flag = "<?php echo $flag;?>";//初始化标记变量
        var guest = "<?php echo $guest;?>";//获取黑棋玩家名称
        var host = "<?php echo $host;?>";//获取红棋玩家名称
        var now_chess = "";//初始化当前棋子的变量为空
        var moved = "";//初始化移动棋子的变量为空
        var eated = "";//初始化吃棋的变量
        var pause_time = 0;//初始化发布信息的时间
        var prompt_pause_time = 0;//初始化提示信息的时间
        var guest_win = <?php echo $guest_win;?>;//黑棋方的赢局次数
        var host_win = <?php echo $host_win;?>;//红棋方的赢局次数
        var game_ended = 0;//初始化游戏结束标记
        var t3 = "";
        function form_chess(chess){       			//自定义函数
            now_chess = chess;						//对当前棋子的变量重新赋值
            var chess_split = chess.split(",");		//分割棋子字符串为数组
            var pla = "<table width=556 height=601 border=0 cellpadding=0 cellspacing=0 bordercolor=#000000 background=images/bg.png><tr><td><table align=center border=0 cellpadding=0 cellspacing=0 width=540 height=601>";
            if(site == "host")
                for(var i = 0;i < 10;i ++){       //设置棋盘中主机的棋子10行9列，并布置主机棋子位置
                    pla += "<tr>";
                    for(j = 0;j < 9;j ++){
                        pla += "<td><div id=chess_"+(i * 9 + j + 1)+"><input type=hidden name=chess_value_"+(i * 9 + j + 1)+" id=chess_value_"+(i * 9 + j + 1)+" value="+chess_split[i * 9 + j]+"><a href=javascript:click_chess("+(i * 9 + j + 1)+")><img alt="+chess_split[i * 9 + j]+","+(i * 9 + j + 1)+" src=images/"+chess_split[i * 9 + j]+".png border=0 width=58px height=58px></a></div></td>";
                    }
                    pla += "</tr>";
                }
            else
                for(var i = 9;i >= 0;i --){        //设置棋盘中客机的棋子10行9列，并布置客机棋子位置
                    pla += "<tr>";
                    for(j = 8;j >= 0;j --){
                        pla += "<td><div id=chess_"+(i * 9 + j + 1)+"><input type=hidden name=chess_value_"+(i * 9 + j + 1)+" id=chess_value_"+(i * 9 + j + 1)+" value="+chess_split[i * 9 + j]+"><a href=javascript:click_chess("+(i * 9 + j + 1)+")><img alt="+chess_split[i * 9 + j]+","+(i * 9 + j + 1)+" src=images/"+chess_split[i * 9 + j]+".png  border=0 width=58px height=58px></a></div></td>";
                    }
                    pla += "</tr>";
                }
            pla += "</table></td></tr></table>";
            return pla;
        }
        var prompt_count=0;
        function open_prompt(message,top,left) {
            prompt_count = 1;
            prompt_pause_time ++;
            if (message){
                document.getElementById('item').style.visibility = "visible";
                document.getElementById('item').style.align ="center";
                document.getElementById('item').style.top = top;
                document.getElementById('item').style.left = left;
                document.getElementById('item').innerHTML = '<table class="message_box"><tr><td valign=middle>系统提示：<br><br>&nbsp;&nbsp;'+message+'</td></tr></table>';
            }
        }
        function close_prompt(){         //关闭提示信息，设置为隐藏
            document.getElementById("item").style.visibility = "hidden";//设置元素为隐藏
            document.getElementById("item").innerHTML =  '';//设置元素中的内容为空
            prompt_pause_time = 0;          //计时功能初始化为0
        }
        var http_request = false;
        function send_request(url) {
            open_prompt((prompt_pause_time>0?'等待对方响应('+prompt_pause_time+'秒）'),'40%','2%');
            if (window.XMLHttpRequest){
                http_request = new XMLHttpRequest();
                if(http_request.overrideMimeType){
                    http_request.overrideMimeType('text/xml');
                }
            }else if (window.ActiveXObject){
                try{
                    http_request =new ActiveXObject("Msxml2.XMLHTTP");
                }catch (e) {
                    try{
                        http_request = new ActiveXObject("Microsoft.XMLHTTP");
                    }catch (e) {}
                }
            }
            if (!http_request){
                alert ('不能创建XMLHttpRequest对象');
                return false;
            }
            http_request.onreadystatechange = processRequest;
            http_request.open('GET',url,false);
            http_request.send(null);
        }
        var text = new Array();
        function processRequest() {
            if (http_request.readyState == 4){
                if(http_request.status == 200){
                    if (http_request.responseText == "ended"){
                        document.location.href = "index.php";
                        text =http_request.responseText.split("|");
                        if (http_request.responseText){
                            t3 = text[3];
                            message_guest = decodeURI(text[8]);
                            message_host = decodeURI(text[9]);
                            guest_win = text[6];
                            host_win = text[7];
                        }
                        if (now_chess !=text[0]&& text[0]){
                        //    对棋子重新布局
                            document.getElementById("pla").innerHTML =form_chess(text[0]);
                        }
                    }
                }
            }
        }
        function send_message(){             //定义发送聊天信息的函数
            var message = document.getElementById('message').value;//获取玩家聊天信息
            if(message != ''){             //如果聊天信息不为空
                var message = encodeURI(encodeURI(message));//对聊天信息进行编码
                send_request('send_message.php?roomid=<?php echo $_GET['id'];?>&message='+message+'&site='+site+'&random='+Math.random());//将聊天信息存储在数据表中
                document.getElementById('message').value = '';                   //消息框清空
                open_prompt('消息发送成功！', '40%', '2%');                     //弹出消息框
            }
        }
    </script>
    <script src="./js/room.js" type="application/javascript"></script>
</head>
<body>
<table align="center" style="padding-top:5%;">
    <tr>
        <td width="210" rowspan="3" valign="top">
            <table width="191" height="100%" border="0" cellpadding="0" cellspacing="0">
                <tr valign="top">
                    <script>document.write("<td height=240 valign='bottom' nowrap background='images/"+(site=='host'?'left1':'left2')+".png'>")</script>
                    <table width="191" height="60" border="0">
                        <tr>
                            <th width="40" height="30" align="right" valign="middle"><div id="top_box_flag" width="100%"></div></th>
                            <th width="130" height="30" align="left" valign="middle"><div id="top_box" width="100%"></div></th>
                            <th width="22" height="30" align="left" valign="middle"></th>
                        </tr>
                        <tr>
                            <td height="30" align="left" valign="middle"></td>
                            <td height="30" align="left" valign="top"><div id="top_box_tongji" width="100%"></div></td>
                            <td height="30" align="left" valign="middle"></td>
                        </tr>
                    </table>
                    </td>
                </tr>
                <tr>
                    <td width="191" height="126" align="center">
                        <a href="javascript:copy_url()"><img src="images/left3.png" style="margin-top:6px;"></a>
                        <script>document.write("<a href=exit.php?roomid=<?php echo $_GET['id'];?>&site="+site+"><img src='images/btn_exit.png' width=90 height=39 style='margin-top:8px;'></a>");</script>
                        <script>if(site == "host") document.write("<a href=end.php?roomid=<?php echo $_GET['id'];?>><img src='images/btn_end.png' width=90 height=39 border=0></a>");</script><br>
                    </td>
                </tr>
                <tr valign="bottom">
                    <script>document.write("<td height=240 valign='bottom' nowrap background='images/"+(site=='host'?'left2':'left1')+".png'>")</script>
                    <table width="191" height="60" border="0">
                        <tr><th width="40" height="30" align="right"><div id=bottom_box_flag width=100%></div></th>
                            <th width="130" align="left"><div id=bottom_box width=100%></div></th>
                            <th width="22" align="left"></th>
                        </tr>
                        <tr><td height="30" align="left"></td>
                            <td height="30" align="left" valign="top"><div id=bottom_box_tongji width=100%></div></td>
                            <td height="30" align="left"></td>
                        </tr>
                    </table>
                    </td>
                </tr>
            </table>
        </td>
        <td width="3" rowspan="3" id="pla">
<!--            <div ></div>-->
        </td>
        <td width="240" align="right" valign=top>
            <table style="position:relative;">
                <tr>
                    <td><img src="images/sign.png" width="220" height="63"></td>
                </tr>
                <tr>
                    <td><img src="images/roomcode.png" width="220" height="70"><div class="roomcode"><?php echo $name;?></div></td>
                </tr>
                <tr>
                    <td width="220" height="260"><div id="item" style="position:absolute; left:0px; top:0px; z-index:1; visibility: hidden;"></div></td>
                </tr>
                <tr>
                    <td width="220" height="201" valign=bottom>
                        <table class="message" cellspacing="0" cellpadding="0">
                            <tr align="left">
                                <td height="45" colspan="3" scope="col" valign=middle>&nbsp;</td>
                            </tr>
                            <tr>
                                <td width="15"></td>
                                <td><div id="message_pla" class="message_chat"></div></td>
                                <td width="15"></td>
                            </tr>
                            <tr>
                                <td height="45" colspan="3" valign="middle" class="message_td">
                                    <input type="text" id="message" name="message" size="18" onBlur="this.focus();" onKeyPress="if(event.keyCode==13) {document.getElementById('button').click();}" />
                                    <input name="button" id="button" type="button" class="message_btn" onClick="send_message()" value="发送" />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<script>
    function get_info() {
        if(site == "guest"){
        //    定义元素中的内容
            document.getElementById('top_box').innerHTML = "<font class='style4'>"+host+"</font>";
            document.getElementById('bottom_box').innerHTML = guest;
            document.getElementById('top_box_tongji').innerHTML = "<font class='style4'>获胜:"+host_win+"局</font>";
            document.getElementById('bottom_box_tongji').innerHTML = "获胜:"+guest_win+"局";
            if(flag == "guest"){
            //    若当前走棋的玩家是黑方，显示黑棋玩家走棋图标
                document.getElementById('bottom_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                // 将元素内容定义为空
                document.getElementById('top_box_flag').innerHTML = "";
            }else {
            //    输出红旗玩家走棋图标
                document.getElementById('top_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                // 将元素内容定义为空
                document.getElementById('buttom_box_flag').innerHTML = "";
            }
        }else if (site == host){
            //    定义元素中的内容
            document.getElementById('bottom_box').innerHTML = "<font class='style4'>"+host+"</font>";
            document.getElementById('top_box').innerHTML = guest;
            document.getElementById('bottom_box_tongji').innerHTML = "<font class='style4'>获胜:"+host_win+"局</font>";
            document.getElementById('top_box_tongji').innerHTML = "获胜:"+guest_win+"局";
            if(flag == "host"){
                //    输出红旗玩家走棋图标
                document.getElementById('bottom_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                // 将元素内容定义为空
                document.getElementById('top_box_flag').innerHTML = "";
            }else {
                //    若当前走棋的玩家是黑方，显示黑棋玩家走棋图标
                document.getElementById('top_box_flag').innerHTML = "<img src='./images/move.gif' width='27' height='16'>";
                // 将元素内容定义为空
                document.getElementById('bottom_box_flag').innerHTML = "";

            }
        }
        if (allow_load == 1){
            pause_time = 0;
            send_request('get_info.php?roomid=<?php echo $_GET['id'];?> &site = '+site+'&random='+Math.random());
            document.getElementById("pla").innerHTML =
                document.getElementById("pla").innerHTML.replace(/<a(.*?)>/ig,"");
            document.getElementById("pla").innerHTML =
                document.getElementById("pla").innerHTML.replace(/<\/a>/ig,"");
        }
        if (pause_time == 3 || host == "" || guest == "" ){
            pause_time = 0;
            send_request('get_info.php?roomid=<?php echo $_GET['id'];?> &site = '+site+'&random='+Math.random());
        }
        pause_time ++;
        if (prompt_count>0){
            if (prompt_count == 3){
                prompt_count = 0;
                close_prompt();
            }else
                prompt_count ++;
        }
    }
    send_request('get_info.php?roomid=<?php echo $_GET['id'];?>&site='+site+'&random='+Math.random());
    get_info();
    setInterval("get_info()",1000);
</script>
</body>
</html>